-- Create 'students' table
CREATE TABLE student (
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         first_name VARCHAR2(100) NOT NULL,
                         last_name VARCHAR2(100) NOT NULL,
                         age NUMBER,
                         address VARCHAR2(255),
                         email VARCHAR2(255) NOT NULL UNIQUE,
                         password VARCHAR2(255) NOT NULL,
                         phone_number VARCHAR2(50) NOT NULL UNIQUE,
                         role VARCHAR2(50) NOT NULL
);

-- Create 'courses' table
CREATE TABLE course (
                        id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                        course_name VARCHAR2(255) NOT NULL,
                        course_code VARCHAR2(100) NOT NULL UNIQUE,
                        course_price NUMBER(10, 2) NOT NULL,
                        course_description VARCHAR2(1000),
                        course_instructor VARCHAR2(255) NOT NULL
);

-- Create 'course_enrollment' table
CREATE TABLE enroll_course (
                               student_id NUMBER NOT NULL,
                               course_id NUMBER NOT NULL,
                               PRIMARY KEY (student_id, course_id),
                               FOREIGN KEY (student_id) REFERENCES student(id) ON DELETE CASCADE,
                               FOREIGN KEY (course_id) REFERENCES course(id) ON DELETE CASCADE
);